### ISSUE TITLE
Temporary address change to be editable or cancellable

### ISSUE THREAD

**Issue by kirstipa** [KSF-Media/affresco#119]
According to customer service most of our customers don't know how long they will use the temporary address. Therefore it would be very useful if there was some way to edit temporary address change in Mitt konto. It could be:

There could be a "cancel" button. If customer wants to edit her temporary address change she could cancel the current one and create a new one.

or/and

There could be "edit" button that enables customer to edit the temporary address change.

And why not add the same feature to upphåll as well.

**Comment by kaol** [comment]
These features have been implemented.
