### ISSUE TITLE
Reclamation feature

### ISSUE THREAD

**Issue by kirstipa** [KSF-Media/affresco#121]
Let's investigate how we could implement reclamation feature to Mitt konto.

User would have a button beside every (printed paper) subscription that enables user to make reclamation. The needed information is:

- which days paper is concerned
- what is the reason for reclamation

The method to use is "CreateDeliveryReclaimForLM" and here's example from Jaicom:

![image002](https://user-images.githubusercontent.com/44430925/59431760-550a9300-8dee-11e9-9e07-f3394075dc97.jpg)

**Comment by vapaj** [comment]
It seems that this will require upgrading Kayak in production.
