### ISSUE TITLE
Way to get receipt

### ISSUE THREAD

**Issue by kirstipa** [KSF-Media/affresco#125]
Some customers need a way to get receipt of their autorenewing purchases.

Perhaps our solution could be a simple list of payments (like HBO) with product name, payment date and cost breakdown (incl. total price and amount of vat).

Can we get this data from Kayak?

Some ideas:

![image](https://user-images.githubusercontent.com/44430925/59681926-be6b1700-91dd-11e9-822d-556ecc64b36c.png)

![image](https://user-images.githubusercontent.com/44430925/59681948-cf1b8d00-91dd-11e9-811d-ae6635677bd6.png)

![image](https://user-images.githubusercontent.com/44430925/59682028-fe31fe80-91dd-11e9-941b-fbd928eff30f.png)

![image](https://user-images.githubusercontent.com/44430925/59682228-726ca200-91de-11e9-8e4a-23467012413f.png)

**Comment by kirstipa** [comment]
Date, price, vat info

**Comment by kaol** [comment]
Done.
