### ISSUE TITLE
Editing the address if there's no address

### ISSUE THREAD

**Issue by kirstipa** [KSF-Media/affresco#138]
If user has no address we still show the "Ändra" button in Mitt Konto. When clicking that "Ändra" there is no field to type the address in.

We should just hide the "Ändra" in case there's no address or have a field where to type in the address.

![image (11)](https://user-images.githubusercontent.com/44430925/61044393-3bef0500-a3e1-11e9-9328-3503d0682324.png)

![image (10)](https://user-images.githubusercontent.com/44430925/61044397-3db8c880-a3e1-11e9-9da6-37a923bbe97b.png)

**Comment by f-f** [comment]
@kirstipa should we instead show something like "Add new address"?

**Comment by kirstipa** [comment]
@f-f Yes, that should work. So we would show "Lägg till addres" instead of "Ändra".

**Comment by vapaj** [comment]
Merged in #183
