### ISSUE TITLE
Merge account error handling

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#14]
Show an error message to the user if merging accounts fails.

**Comment by f-f** [comment]
I recall I implemented some error handling, but I guess we're missing some edge cases?

**Comment by vapaj** [comment]
This occurs at least when Persona returns `500`.

**Comment by f-f** [comment]
This is being fixed by #29 right? Or should we have a separate handling in the Login component?

**Comment by vapaj** [comment]
Right. Technically the `500` Persona returned (because of #32) isn't a login specific error, whereas `InvalidCredentials`, `FacebookEmailMissing` or `EmailMismatchError` are. So I guess it's fine this is handled somewhere else.

**Comment by f-f** [comment]
I'm not sure, I'd go for the policy of "the Login component should take care of all Persona interaction and the parent should have no idea there's an HTTP service behind"
