### ISSUE TITLE
HBL 365 onboarding URL

### ISSUE THREAD

**Issue by kirstipa** [KSF-Media/affresco#251]
We need to create these two URLs:

iOS: https://onboarding-ios-hbl365.ksfmedia.fi/
Android: https://onboarding-android-hbl365.ksfmedia.fi/

Both pages will contain same content (but we might want to update them separately in the future).

Texts to show on that page:

Välkommen till den nya HBL 365-appen!

Du loggar in med samma uppgifter som tidigare,

Det här är nytt:
Nu finns fyra tidningar: HBL, Östnyland, Västra Nyland och Hangötidningen
I vyn Senaste nytt hittar du de senaste nyheterna
Du kan nu läsa artiklar i e-tidningen också i en särskild artikelvy 
I artikelvyn kan du lyssna på artikeln
Sökfunktionen hjälper dig hitta de nyheter du söker

Trevliga lässtunder med den nya appen!

**Comment by vapaj** [comment]
Moved to this repo https://github.com/KSF-Media/statisk (https://github.com/KSF-Media/statisk/pull/16)
