### ISSUE TITLE
Think about monorepo deploy

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#290]
Currently, apps in our monorepo are deployed only when there are changes under the app directory. We have the `.build-size-sha256` files to trigger deploys, but we need to change these by hand (by hand I mean triggering [this perl script](https://github.com/KSF-Media/affresco/blob/master/hooks/pre-commit)), and it's hard to remember.

I wish there were a better way of doing this.

**Comment by ae-mo** [comment]
Can't we make the script create an additional commit containing the updated hashes?

**Comment by ae-mo** [comment]
I think this is outdated @vapaj ?

**Comment by vapaj** [comment]
Indeed 🤠
