### ISSUE TITLE
Add handling of footnotes and questions

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#293]
We'll have two new objects in the body of the article: `footnote` and `question`. Let's handle those.

**Comment by pikkuruusu** [comment]
Style specs:

Question:
![image](https://user-images.githubusercontent.com/7558771/76970496-a410c600-6934-11ea-8d29-e08fcf159281.png)


Footnotes:
![image](https://user-images.githubusercontent.com/7558771/76970461-94917d00-6934-11ea-8ee8-f3421201736b.png)

**Comment by lulzimfazlija** [comment]
any uuid for such article that contains footnote and question?

**Comment by pikkuruusu** [comment]
UUID for text question: 3f1bc407-af01-46e6-96a1-8f41065ffccc
The "Hur skulle du beskriva situationen för tillfället?" is one example.

Footnote example: 301ca007-4061-42c9-b93e-a00097fbe6af
It's the "Källor:..." part on the bottom.

I guess the new objects are still in stager version.

**Comment by vapaj** [comment]
Merged in #298
