### ISSUE TITLE
Handle SubscriptionExists

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#299]
While we are checking if the customer already has the subscription in Vetrina, the client side and server side might not be in sync. So handle `SubscriptionExists` errors we get from Bottega.

**Comment by ae-mo** [comment]
@vapaj so after we have the info about a duplicate subscription from `bottega`, I guess we need to show an error view, correct?

**Comment by vapaj** [comment]
We need to think about a behaviour for that, it's not really an error from the UX point of view. The simplest solution would be to just close vetrina by calling the `onClose` prop.
