### ISSUE TITLE
Add som extra markers for ads in app article view

### ISSUE THREAD

**Issue by pikkuruusu** [KSF-Media/affresco#316]
We want to make it a bit clearer that an ad is an ad. So we want to add a line before the ad and move the word "ANNONS" to center. We also want to add line after ad and add the words "ANNONS SLUT".

Example:

![image (2)](https://user-images.githubusercontent.com/7558771/78232135-7c952e00-74dc-11ea-8a44-1b6b7afe6948.png)

**Comment by lulzimfazlija** [comment]
I think this needs to be redesigned from **https://script.ksfmedia.fi/app/gamAppAds.min.js"** currently this file decides how the ads should be looking and I dont have access to this. I guess Joachim does!

**Comment by lulzimfazlija** [comment]
ofc there might be some workaround to style this from the react part but I think it would be kinda dirty and take more time, so I presume you should handle that from the link i posted above!

**Comment by pikkuruusu** [comment]
Thanks, I’ll check with Joachim.

**Comment by jockeF** [comment]
This change is now in the repo.
