### ISSUE TITLE
Log in existing user

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#324]
Add styles for logging in existing user
![vetrina_existing_account](https://user-images.githubusercontent.com/6303323/78636728-8c808980-78b1-11ea-8c5e-d6ff6bf45b96.png)

**Comment by pikkuruusu** [comment]
Some proofreading:
It should be `KSF Media-lösenord` with a hyphen.

**Comment by ae-mo** [comment]
Should we close this?
