### ISSUE TITLE
Error view

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#336]
Add an error view according to:
![image (1)](https://user-images.githubusercontent.com/6303323/79537880-e04a5a00-808b-11ea-90c8-8b88b25af106.png)

However, the correct text should be

```
Något gick fel med ditt inköp!
Klicka nedan för pröva på nytt eller ta kontakt med vår kundservice på pren@hbl.fi.
Vi beklagar strulet!
Pröva på nytt
```

**Comment by ae-mo** [comment]
Can we make a list of the scenarios where we would like to show this view?

I mean the concrete points in the application so far.

**Comment by ae-mo** [comment]
@vapaj I've made a draft PR (#341), so we could maybe discuss how to proceed.

**Comment by vapaj** [comment]
I forgot this, but the border color should be #DC001A
