### ISSUE TITLE
Handle invalid credentials

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#342]
Currently we are rendering the error view when user inserts invalid credentials.

We should rather show similar error message what we have in the `User` component:
![Screenshot_2020-04-28 Mitt Konto](https://user-images.githubusercontent.com/6303323/80459009-64c59400-893a-11ea-84c1-aab0ead10f2c.png)

**Comment by ae-mo** [comment]
https://github.com/KSF-Media/affresco/blob/master/packages/vetrina/src/Vetrina/Purchase/NewPurchase.purs#L172-L181

I think there is an issue in this part of `vetrina`'s code: we don't save the error we receive from the server, which might be an `AuthenticationError`, i.e. the one we need to be aware of in order to show the text. 

First of all, @vapaj do you agree? And if so, what would you suggest?

**Comment by vapaj** [comment]
If I understood you correctly, that place you pointed out is for the form validation, not where we handle server errors. Should probably make that clearer in the code 🤔

So the first function to pass to `unV` is called if the form validations do not pass, and the second one is called if the form is valid (https://pursuit.purescript.org/packages/purescript-validation/4.2.0/docs/Data.Validation.Semigroup#v:unV)

Here is the case analysis for the server errors:
https://github.com/KSF-Media/affresco/blob/master/packages/vetrina/src/Vetrina/Vetrina.purs#L337-L344

**Comment by ae-mo** [comment]
> Here is the case analysis for the server errors:
> https://github.com/KSF-Media/affresco/blob/master/packages/vetrina/src/Vetrina/Vetrina.purs#L337-L344

I actually was aware of it, so silly of me 😅 but like this server errors are handled in the `Vetrina` module, while the text is to be rendered in the `NewPurchase` component, so I guess what I'm asking is: what's a proper way to make the `NewPurchase` component aware of an `AuthenticationError`?

**Comment by vapaj** [comment]
Good question. Indeed, this is not simple 😄 

Perhaps we could have another parameter to `ExistingAccount` (https://github.com/KSF-Media/affresco/blob/master/packages/vetrina/src/Vetrina/Types.purs#L11), like `ExistingAccount String (Maybe AuthErr)`. Or, we could also take an array of `a`, where `a` is some of input field type, like in `NewPurchase`: https://github.com/KSF-Media/affresco/blob/master/packages/vetrina/src/Vetrina/Purchase/NewPurchase.purs#L53-L57.

Then we would look for the combination of `EmailAddress`  and `Password` in that array, and assume the credentials were invalid.

However, if the parameters for `ExistingAccount` are `ExistingAccount String (Array a)`, we'll probably wonder later what is this `Array a` and why the hell does this expect an array of input fields. It might be a good idea to declare a type alias for this, so we'll know what's that about.
```purescript
type AccountInvalidInputFields a = Array a
```
You might think, "but wait, why can't we just use `Either (Array a) String`?", but we cannot, as we do need the existing account email address there (the `String`) in any case.

**Comment by ae-mo** [comment]
It makes sense to me, I am just wondering what's the added value of the array approach with respect to the `ExistingAccount String (Maybe AuthErr)`.

Is it because there might be other kinds of error in the future?

**Comment by vapaj** [comment]
I guess we can start with the `Maybe AuthErr` approach (think of a better name for it though) and adjust it when/if we ever need to.
