### ISSUE TITLE
Unexpected server error view

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#352]
Add view for an unexpected non-user-related error that we don't know how to recover from, like not getting a proper `Product` as a prop.

**Comment by ae-mo** [comment]
Could we reuse the error view we already have and do case analysis on the type of error maybe?

**Comment by vapaj** [comment]
Absolutely!

**Comment by ae-mo** [comment]
Do we need a different message from the one we are using now in the error view?

**Comment by vapaj** [comment]
I suppose, as this is not a user related error. Currently we are saying:
"Something went wrong with your purchase. Try again or contact customer service."

It's not exactly the case here.

**Comment by ae-mo** [comment]
Resume (my understanding): we need to make the `vetrina` react component accept some `JSX` from the embedding code, so that it is rendered in case of failure in parsing the product list.
