### ISSUE TITLE
Show the history of transactions

### ISSUE THREAD

**Issue by ae-mo** [KSF-Media/affresco#407]
Show the history of transactions made by the customer in `mitt-konto`. 

Probably the way to go would be to open a modal containing a paged list. 

IMPORTANT: we need to show tax information for each transaction (actual numbers!).

**Comment by vapaj** [comment]
Related: https://github.com/KSF-Media/affresco/issues/125

**Comment by vapaj** [comment]
Also please let's not use modals if we can avoid them 😁
