### ISSUE TITLE
Add Cusno type

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#439]
It seems there are wild cusnos everywhere in our code, sometimes it's an `Int`, sometimes a `String`:
https://github.com/KSF-Media/affresco/blob/master/packages/components/src/Api/Subscription.purs#L32
https://github.com/KSF-Media/affresco/blob/master/packages/components/src/Persona.purs#L346

Let's create a `newtype Cusno` for this.

**Comment by ae-mo** [comment]
There are also wild `subsno`s, we should really unify those types.

**Comment by kaol** [comment]
This started to be bothersome when I tried to compare subscription's paycusno to the logged in user's cusno, I could as well fix this.
