### ISSUE TITLE
Fetch user's credit cards on user data fetch

### ISSUE THREAD

**Issue by ae-mo** [KSF-Media/affresco#454]
In **mitt-konto**, the credit cards of a user are fetched upon rendering the component containing the editing actions available for the account (`MittKonto.AccountEdit`). The button to update a credit card is shown only if the user has a credit card. 

The problem with this is that the button appears after the generic loader we display at login has disappeared.

We should fetch the credit cards while the loader is being displayed, i.e. at the same time when/right after we fetch user data.

Releted to #412.

**Comment by kaol** [comment]
Superseded by changes to credit card handling.
