### ISSUE TITLE
Unmatched routes return error

### ISSUE THREAD

**Issue by ae-mo** [KSF-Media/affresco#510]
Don't know where to exactly leave this comment to, but the `noMatchRoute` does not work anymore in this branch 🤔 So for instance `http://localhost:8000/asdasdasds` should render the mitt konto front page but it doesn't

_Originally posted by @vapaj in https://github.com/KSF-Media/affresco/issues/504#issuecomment-768176875_

**Comment by vapaj** [comment]
Merged in #523
