### ISSUE TITLE
Show loading status on login button in the login component

### ISSUE THREAD

**Issue by pikkuruusu** [KSF-Media/affresco#597]
When the user logins we could change the button text from `Logga in` to `Loggar in` and add some animated dots after the text when loading. Like this:

![logga-in-animation](https://user-images.githubusercontent.com/7558771/114362818-72425100-9b80-11eb-97a0-2d9567502e4d.gif)

**Comment by vapaj** [comment]
Also, let's make it gray when loading (to indicate the button is disabled for the time)
