### ISSUE TITLE
hbl-fallback-img-error would need fixing

### ISSUE THREAD

**Issue by pikkuruusu** [KSF-Media/affresco#623]
Sometimes we get this error in the app-article:

<img width="827" alt="Skärmavbild 2021-04-29 kl  15 55 46" src="https://user-images.githubusercontent.com/7558771/116554281-adc07780-a903-11eb-9f8f-329517b969eb.png">

This seems to be causing problems for our analytics so we should check this and fix it.

**Comment by vapaj** [comment]
Fixed image in #626, was not related to analytics problems.
